baseURL = 'http://divo.blog/'
languageCode = 'en-us'
title = 'Steven Diviney'
theme = "hugo-theme-monochrome"

[[menu.navbar]]
identifier = "about"
name = "about"
title = "about"
url = "/about/"
weight = 100

[[menu.navbar]]
identifier = "apps"
name = "apps"
url = "/apps/"
weight = -100
